name: tracker-gpu8

dependencies:
  - python==3.8
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit==10.1.243
  - pip:
    - tensorflow-gpu==2.2.0
    - lxml
    - tqdm
    - seaborn
    - pillow
